### ISSUE TITLE
Not So Abandoned - back in business 

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-invoice-ninja#2]
So, I have been working closely with Landis on getting an Odoo appliance in the TKL library. I am happy to say it looks like it's going to happen. While working on getting this TurnKey'ed I found that this is very powerful software that would replace this software. 

I started work on this repo to replace my invoicing system. Sadly I found Odoo and I am abandon this work. If you want to adopt this repo please post a reply to this issue. If no one has reposed by the end of the year I will deleted it.

**Comment by JedMeister** [comment]
I reckon we'll probably adopt it to include in the TKL repo as a simple invoice appliance is nice. Bamboo incvoice is dead and simpleinvoice is essentially just in a basic maintence mode (no further development) so it would still be good to have invoice ninja IMO.

Totally understand that you don't want to do it though! :smile:

**Comment by DocCyblade** [comment]
If I don't get any takers I'll do this IF I have time. Got few projects in the air :-)

**Comment by JedMeister** [comment]
You do! :stuck_out_tongue_winking_eye:

**Comment by hailthemelody** [comment]
Hi @DocCyblade I've been checking out Odoo Invoicing as well, though it seems like overkill for smaller shops. Overall do you see Odoo as a better solution compared to Invoice Ninja? I ask as you mentioned you left supporting Invoice Ninja in favor of Odoo. Thanks for your work!

**Comment by DocCyblade** [comment]
@hailthemelody Odoo is nice but like you said its a lot of stuff. I am working on Odoo as that's the software I am using for my self. If there is enough supporters for this to be a turnkey Linux app I'll put back on the burners for sure

**Comment by DocCyblade** [comment]
So I am looking to get is back and going for those who are interested. Will be a few weeks before I can start back up but I am going over my notes and code to see where I left off.

**Comment by hailthemelody** [comment]
Hey Doc! As far as my own interested are concerned, I'm actually about to migrate from Invoice Ninja to Odoo as my needs have grown since we last chatted. I just wish they'd make the new v10 interface available on the community version :/

Hope the TKL project goes well.

**Comment by DocCyblade** [comment]
Thanks, would you be a willing co-sponsor? I need some one who can put the app through a good testing. I know when working with Odoo having someone who could test the release that used the software was a huge help. Since you use Invoice ninja it would be a huge help. Also are you talking about v10 of Odoo or Invoice?

**Comment by hailthemelody** [comment]
Absolutely Doc, and thank your for asking for my involvement. I have various environments that I can setup tests for as well if you like, including bare metal, VM (ESXi and XenServer), and cloud (AWS, Digital Ocean, and Vultr). More if you need it, though that should have you covered for usage cases.

**Comment by DocCyblade** [comment]
@hailthemelody - Sounds great! I'll tag you on an issue when we are ready to give it a spin and/or just star this repo and keep tabs on it. Welcome to the team :-)
 
 I know TKLDev makes an ISO, and TKL usually has a view other downloads. Mostly my testing is via the ISO using VMWare. I will have soon a Proxmox server but thats still new territory for my self, so I'll stick to what I know. 

Maybe @JedMeister can shed some light on building for others (Xen/VM/etc..)

I know when I worked on Odoo, I primarily used the ISO to VMWare and ran through the install. Can you/have you built any ISOs your self with TKL, if not I could always post the ISO on a private share or public for that matter, I think I still have access to source forge ( @JedMeister  is that still true if I want to push and ISO there for testing?)


I have a need right now for Mayan EDMS and thats my focus right now, after I get a beta done for that I swing back around to this.

**Comment by JedMeister** [comment]
You can build to any of the targets TurnKey supports with the addition of [buildtasks](https://github.com/turnkeylinux/buildtasks) to your TKLDev server. It's not very well documented but we can resolve that at some point...

I have a custom local buildtasks script that builds apps straight to LXC container and uploads them straight to my Proxmox host. I'll share that with you when you're ready! :smile: 

Yes you should still have access to the community SF project.

**Comment by DocCyblade** [comment]
@JedMeister - not sure how I missed your above post regarding the build tasks!

**Comment by DocCyblade** [comment]
@hailthemelody - This project might start rolling by the middle of November. I am already starting to do some research and work on this repo, cleaning up and getting it ready. I had a quick look, this seems rather quick as most of the prerequisites are in the LAMP appliance! I could have a Alpha build rather quickly, with betas following quickly after that.
